title: Operator Fabric Public Web Site
description: OperatorFabric is a modular, extensible, industrial-strength and field-tested platform for use in electricity, water, and other utility operations.
url: opfab.github.io/operatorfabric/
logo: /assets/images/favicon.png

sass:
  sass_dir: assets/styles
plugins:
  - jekyll-seo-tag